// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfrE40UsaQxZ7TpZAlTCqImtZeMfq7sOo',
    appId: '1:839313874487:web:9c4ec1a914b698cd0229b2',
    messagingSenderId: '839313874487',
    projectId: 'continual-mind-388823',
    authDomain: 'continual-mind-388823.firebaseapp.com',
    storageBucket: 'continual-mind-388823.appspot.com',
    measurementId: 'G-FNHF0DP6LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKh2T4kk41pV_NaEbwkawrEejFqn0zD4c',
    appId: '1:839313874487:android:a0410c5b3c08a43c0229b2',
    messagingSenderId: '839313874487',
    projectId: 'continual-mind-388823',
    storageBucket: 'continual-mind-388823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTFcU8Jc6XAbkteq4SLq8maiXca4FpgKU',
    appId: '1:839313874487:ios:fdf31b5810addcf70229b2',
    messagingSenderId: '839313874487',
    projectId: 'continual-mind-388823',
    storageBucket: 'continual-mind-388823.appspot.com',
    iosClientId:
        '839313874487-rdbq4q48hpog2no3oofu89a8rmd6mk7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.wlLeadGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTFcU8Jc6XAbkteq4SLq8maiXca4FpgKU',
    appId: '1:839313874487:ios:d8530bc27f11e0cd0229b2',
    messagingSenderId: '839313874487',
    projectId: 'continual-mind-388823',
    storageBucket: 'continual-mind-388823.appspot.com',
    iosClientId:
        '839313874487-dnt9m1vspgrpmgkn2c7uptob6e8vk0po.apps.googleusercontent.com',
    iosBundleId: 'com.example.wlLeadGenerator.RunnerTests',
  );
}
